=== FrancoStival/Ejercicios-DAM/HTML/XML/Activitat 6/botiga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.dam.cat/botigaEsportiva"
           xmlns="http://www.dam.cat/botigaEsportiva">

    <xs:element name="botiga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="productes" type="productesType"/>
                <xs:element name="equips" type="equipsType"/>
                <xs:element name="vendes" type="vendesType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="productesType">
        <xs:sequence>
            <xs:element name="producte" type="producteType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="producteType">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="nom" type="xs:string" use="required"/>
        <xs:attribute name="esport" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="futbol"/>
                    <xs:enumeration value="bÃ squet"/>
                    <xs:enumeration value="handbol"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="talla" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="S"/>
                    <xs:enumeration value="M"/>
                    <xs:enumeration value="L"/>
                    <xs:enumeration value="XL"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="preu" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="10"/>
                    <xs:maxExclusive value="150"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="equip_ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="equipsType">
        <xs:sequence>
            <xs:element name="equip" type="equipType" maxOccurs="2"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="equipType">
        <xs:sequence>
            <xs:element name="esports" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="nom" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vendesType">
        <xs:sequence>
            <xs:element name="venda" type="vendaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vendaType">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="producte_ref" type="xs:IDREF" use="required"/>
        <xs:attribute name="data_venda" type="xs:date" use="required"/>
        <xs:attribute name="quantitat" type="xs:integer" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                    <xs:maxInclusive value="5"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="venedor" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== FrancoStival/Ejercicios-DAM/XML/Activitat 6/botiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<botiga xmlns="http://www.dam.cat/botigaEsportiva"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.dam.cat/botigaEsportiva botiga.xsd">
    <productes>
        <producte id="p1" nom="Samarreta FC Barcelona" esport="futbol" talla="M" preu="89.99" equip_ref="e1"/>
        <producte id="p2" nom="Pantalons FC Barcelona" esport="handbol" talla="L" preu="79.99" equip_ref="e1"/>
        <producte id="p3" nom="Samarreta Madrid" esport="bàsquet" talla="XL" preu="109.99" equip_ref="e2"/>
    </productes>
    <equips>
        <equip id="e1" nom="FC Barcelona">
            <esports>futbol</esports>
            <esports>handbol</esports>
        </equip>
        <equip id="e2" nom="Real Madrid">
            <esports>bàsquet</esports>
        </equip>
    </equips>
    <vendes>
        <venda id="v1" producte_ref="p1" data_venda="2024-01-01" quantitat="2"/>
        <venda id="v2" producte_ref="p3" data_venda="2024-01-02" quantitat="1" venedor="Marta"/>
    </vendes>
</botiga>
